import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { X } from "lucide-react";
import { homologacionProductoSchema } from "../../facturas/schemas/siat.schemas";
import { guardarHomologacionProducto, listarCatalogosHomologacion } from "../../facturas/services/siat.service";
import type { ProductoHomologacion } from "../../facturas/types/siat.types";
import { SiatError, SiatLoading } from "../../facturas/components/SiatShared";
import "../../facturas/styles/siat.css";

export default function ProductoHomologacionModal({producto,onClose}:{producto:ProductoHomologacion|null;onClose:()=>void}){
 const [form,setForm]=useState({codigoProductoSin:producto?.codigoProductoSin??"",actividadEconomica:producto?.actividadEconomica??"",unidadMedidaSin:producto?.unidadMedidaSin??"",origen:producto?.origen??"IMPORTADO",versionCatalogo:producto?.versionCatalogo??""}); const [message,setMessage]=useState<string|null>(null); const client=useQueryClient();
 const catalogs=useQuery({queryKey:["siat-catalogos-homologacion"],queryFn:listarCatalogosHomologacion,enabled:Boolean(producto)});
 const save=useMutation({mutationFn:async()=>{if(!producto)return;const parsed=homologacionProductoSchema.safeParse(form);if(!parsed.success)throw new Error(parsed.error.issues[0]?.message??"Revisa los datos.");await guardarHomologacionProducto(producto,parsed.data)},onSuccess:async()=>{await client.invalidateQueries({queryKey:["siat-productos-homologacion"]});onClose()},onError:e=>setMessage(e.message)});
 if(!producto)return null; const change=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v})); return <div className="siat-modal-backdrop" onMouseDown={onClose}><form className="siat-modal siat-small-modal" onSubmit={e=>{e.preventDefault();save.mutate()}} onMouseDown={e=>e.stopPropagation()}><header><div><small>Catálogos SIAT vigentes</small><h2>Homologar {producto.nombre}</h2></div><button type="button" onClick={onClose}><X/></button></header>{catalogs.isLoading&&<SiatLoading/>}{catalogs.error&&<SiatError message={catalogs.error.message}/>}<div className="siat-form-grid two"><label className="wide"><span>Actividad económica</span><select value={form.actividadEconomica} onChange={e=>change("actividadEconomica",e.target.value)}><option value="">Selecciona</option>{catalogs.data?.actividades.map(x=><option key={x.codigo} value={x.codigo}>{x.codigo} · {x.descripcion}</option>)}</select></label><label className="wide"><span>Producto/servicio SIN</span><select value={form.codigoProductoSin} onChange={e=>change("codigoProductoSin",e.target.value)}><option value="">Selecciona</option>{catalogs.data?.productosServicios.map(x=><option key={x.codigo} value={x.codigo}>{x.codigo} · {x.descripcion}</option>)}</select></label><label><span>Unidad de medida SIN</span><select value={form.unidadMedidaSin} onChange={e=>change("unidadMedidaSin",e.target.value)}><option value="">Selecciona</option>{catalogs.data?.unidadesMedida.map(x=><option key={x.codigo} value={x.codigo}>{x.codigo} · {x.descripcion}</option>)}</select></label><label><span>Origen</span><select value={form.origen} onChange={e=>change("origen",e.target.value)}><option value="IMPORTADO">Importado</option><option value="NACIONAL">Nacional</option><option value="SERVICIO">Servicio</option></select></label><label className="wide"><span>Versión de catálogo sincronizada</span><input value={form.versionCatalogo} onChange={e=>change("versionCatalogo",e.target.value)} placeholder="Se obtiene al sincronizar catálogos"/></label></div>{catalogs.data&&catalogs.data.actividades.length===0&&<p className="siat-form-message error">Primero deben sincronizarse los catálogos oficiales. No se usan códigos inventados.</p>}{message&&<p className="siat-form-message error">{message}</p>}<footer className="siat-modal-actions"><button type="button" className="siat-secondary-button" onClick={onClose}>Cancelar</button><button className="siat-primary-button" disabled={save.isPending||!catalogs.data?.actividades.length}>Guardar homologación</button></footer></form></div>
}
