import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Building2, KeyRound, LockKeyhole, RefreshCw, Save, X } from "lucide-react";
import { configuracionSiatSchema } from "../schemas/siat.schemas";
import { guardarConfiguracionSiat, guardarMapeosMetodosPago, guardarPuntoVentaSiat, guardarSucursalSiat, listarSucursalesSiat, obtenerConfiguracionSiat, obtenerMapeosMetodosPago } from "../services/siat.service";
import type { SiatConfiguracion } from "../types/siat.types";
import { obtenerSaludGatewaySiat, sincronizarSiat, solicitarCufdSiat, solicitarCuisSiat, verificarServicioSiat } from "../services/siat.gateway.service";
import { SiatError, SiatLoading } from "./SiatShared";

function ConfigForm({ initial }: { initial: SiatConfiguracion }) {
  const [form, setForm] = useState(initial);
  const [message, setMessage] = useState<string | null>(null);
  const client = useQueryClient();
  const branches = useQuery({ queryKey: ["siat-sucursales"], queryFn: listarSucursalesSiat });
  const selectedBranch = branches.data?.find((item) => item.id === form.sucursalPredeterminadaId);
  const mutation = useMutation({ mutationFn: guardarConfiguracionSiat, onSuccess: async () => { setMessage("Configuración estructural guardada."); await client.invalidateQueries({ queryKey: ["siat-configuracion"] }); }, onError: (error) => setMessage(error.message) });
  function field<K extends keyof SiatConfiguracion>(key: K, value: SiatConfiguracion[K]) { setForm((current) => ({ ...current, [key]: value })); setMessage(null); }
  function submit(event: React.FormEvent) { event.preventDefault(); const parsed = configuracionSiatSchema.safeParse({ ...form, ambiente: "PRUEBAS" }); if (!parsed.success) { setMessage(parsed.error.issues[0]?.message ?? "Revisa los datos."); return; } mutation.mutate(parsed.data); }
  return <form className="siat-card siat-config-form" onSubmit={submit}><div className="siat-card-title"><div><h3>Datos no secretos del emisor</h3><p>Token, certificado y clave privada permanecen exclusivamente en el gateway.</p></div><LockKeyhole /></div><div className="siat-form-grid">
    <label><span>NIT</span><input value={form.nit} onChange={(e) => field("nit", e.target.value)} /></label><label><span>Razón social</span><input value={form.razonSocial} onChange={(e) => field("razonSocial", e.target.value)} /></label><label><span>Nombre comercial</span><input value={form.nombreComercial} onChange={(e) => field("nombreComercial", e.target.value)} /></label><label><span>Municipio</span><input value={form.municipio} onChange={(e) => field("municipio", e.target.value)} /></label><label className="wide"><span>Domicilio</span><input value={form.domicilio} onChange={(e) => field("domicilio", e.target.value)} /></label><label><span>Teléfono</span><input value={form.telefono} onChange={(e) => field("telefono", e.target.value)} /></label><label><span>Código sistema</span><input value={form.codigoSistema} onChange={(e) => field("codigoSistema", e.target.value)} /></label><label><span>Modalidad</span><select value={form.modalidad} onChange={(e) => field("modalidad", e.target.value as SiatConfiguracion["modalidad"])}><option value="COMPUTARIZADA">Computarizada</option><option value="ELECTRONICA">Electrónica</option></select></label><label><span>Documento sector</span><input value={form.documentoSector} onChange={(e) => field("documentoSector", e.target.value)} inputMode="numeric" /></label><label><span>Tipo factura</span><input value={form.tipoFactura} onChange={(e) => field("tipoFactura", e.target.value)} inputMode="numeric" /></label><label><span>Actividad económica</span><input value={form.actividadEconomica} onChange={(e) => field("actividadEconomica", e.target.value)} /></label><label><span>Versión</span><select value={form.versionNormativa} onChange={(e) => field("versionNormativa", e.target.value as SiatConfiguracion["versionNormativa"])}><option value="SIAT_VIGENTE">SIAT vigente</option><option value="SIAT_LEY_1733_PILOTO">Ley 1733 · piloto deshabilitado</option></select></label><label><span>Ambiente</span><input value="PRUEBAS" disabled /></label><label><span>Zona horaria</span><input value="America/La_Paz" disabled /></label><label><span>Integración</span><select value={form.siatHabilitado ? "SI" : "NO"} onChange={(e) => field("siatHabilitado", e.target.value === "SI")}><option value="NO">Deshabilitada</option><option value="SI">Preparar ambiente de pruebas</option></select></label>
    <label><span>Sucursal predeterminada</span><select value={form.sucursalPredeterminadaId} onChange={(e) => { field("sucursalPredeterminadaId", e.target.value); field("puntoVentaPredeterminadoId", ""); }}><option value="">Selecciona</option>{branches.data?.filter((item) => item.activo).map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.nombre}</option>)}</select></label><label><span>Punto de venta</span><select value={form.puntoVentaPredeterminadoId} onChange={(e) => field("puntoVentaPredeterminadoId", e.target.value)}><option value="">Sin punto de venta</option>{selectedBranch?.puntosVenta.filter((item) => item.activo).map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.nombre}</option>)}</select></label>
  </div>{message && <p className={mutation.isError ? "siat-form-message error" : "siat-form-message"}>{message}</p>}<footer><button className="siat-primary-button" type="submit" disabled={mutation.isPending}><Save />{mutation.isPending ? "Guardando…" : "Guardar"}</button></footer></form>;
}

function Operations() {
  const client = useQueryClient(); const [message, setMessage] = useState<string | null>(null);
  const health = useQuery({ queryKey: ["siat-gateway-health"], queryFn: obtenerSaludGatewaySiat, retry: false });
  const operation = useMutation({ mutationFn: async (action: "verify" | "cuis" | "cufd" | "sync") => action === "verify" ? verificarServicioSiat() : action === "cuis" ? solicitarCuisSiat() : action === "cufd" ? solicitarCufdSiat() : sincronizarSiat(), onSuccess: async () => { setMessage("Operación aceptada por el gateway."); await client.invalidateQueries({ queryKey: ["siat-gateway-health"] }); }, onError: (error) => setMessage(error.message) });
  return <section className="siat-card"><div className="siat-card-title"><div><h3>Operación del gateway</h3><p>Estado real del backend; no se muestran secretos.</p></div><Activity /></div>{health.isLoading && <SiatLoading label="Consultando gateway…" />}{health.error && <SiatError message={health.error.message} />}{health.data && <div className="siat-operation-grid"><span><small>Token delegado</small><strong>{health.data.secretos.token ? "Configurado" : "No configurado"}</strong></span><span><small>Firma electrónica</small><strong>{health.data.secretos.firma ? "Configurada" : "No configurada"}</strong></span><span><small>CUIS</small><strong>{health.data.cuis?.fecha_expiracion ? new Date(health.data.cuis.fecha_expiracion).toLocaleString("es-BO") : "No vigente"}</strong></span><span><small>CUFD</small><strong>{health.data.cufd?.fecha_expiracion ? new Date(health.data.cufd.fecha_expiracion).toLocaleString("es-BO") : "No vigente"}</strong></span></div>}<div className="siat-operation-actions"><button type="button" className="siat-secondary-button" onClick={() => operation.mutate("verify")} disabled={operation.isPending}><Activity />Verificar servicio</button><button type="button" className="siat-secondary-button" onClick={() => operation.mutate("cuis")} disabled={operation.isPending}><KeyRound />Solicitar CUIS</button><button type="button" className="siat-secondary-button" onClick={() => operation.mutate("cufd")} disabled={operation.isPending}><KeyRound />Solicitar CUFD</button><button type="button" className="siat-primary-button" onClick={() => operation.mutate("sync")} disabled={operation.isPending}><RefreshCw />Sincronizar</button></div>{message && <p className={`siat-form-message${operation.isError ? " error" : ""}`}>{message}</p>}</section>;
}

const METODOS_INTERNOS = ["EFECTIVO", "TARJETA", "TRANSFERENCIA", "QR", "OTRO"] as const;
function PaymentMappings() {
  const query = useQuery({ queryKey: ["siat-mapeos-pago"], queryFn: obtenerMapeosMetodosPago });
  return <section className="siat-card"><div className="siat-card-title"><div><h3>Métodos de pago SIAT</h3><p>Mapeo obligatorio contra la paramétrica oficial sincronizada; no se usan códigos inventados.</p></div><KeyRound /></div>{query.isLoading && <SiatLoading />}{query.error && <SiatError message={query.error.message} />}{query.data && <PaymentMappingsForm key={JSON.stringify(query.data.mapeos)} data={query.data} />}</section>;
}

function PaymentMappingsForm({ data }: { data: Awaited<ReturnType<typeof obtenerMapeosMetodosPago>> }) {
  const client = useQueryClient(); const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(data.mapeos.map((item) => [item.metodoInterno, item.codigoMetodoPago]))); const [message, setMessage] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: () => guardarMapeosMetodosPago(METODOS_INTERNOS.map((metodoInterno) => ({ metodoInterno, codigoMetodoPago: values[metodoInterno] ?? "" }))), onSuccess: async () => { setMessage("Mapeos de pago guardados."); await client.invalidateQueries({ queryKey: ["siat-mapeos-pago"] }); }, onError: (error) => setMessage(error.message) });
  return <><div className="siat-form-grid">{METODOS_INTERNOS.map((method) => <label key={method}><span>{method}</span><select value={values[method] ?? ""} onChange={(event) => setValues((current) => ({ ...current, [method]: event.target.value }))}><option value="">Selecciona</option>{data.opciones.map((item) => <option key={item.codigo} value={item.codigo}>{item.codigo} · {item.descripcion}</option>)}</select></label>)}</div><div className="siat-operation-actions"><button type="button" className="siat-primary-button" disabled={mutation.isPending || !data.opciones.length} onClick={() => mutation.mutate()}><Save />Guardar mapeos</button></div>{message && <p className={`siat-form-message${mutation.isError ? " error" : ""}`}>{message}</p>}</>;
}

function Branches() {
  const query = useQuery({ queryKey: ["siat-sucursales"], queryFn: listarSucursalesSiat });
  const client = useQueryClient();
  const [branch, setBranch] = useState({ codigo: "", nombre: "", municipio: "", direccion: "" });
  const [point, setPoint] = useState({ sucursalId: "", codigo: "", nombre: "" });
  const branchMutation = useMutation({ mutationFn: guardarSucursalSiat, onSuccess: async () => { setBranch({ codigo: "", nombre: "", municipio: "", direccion: "" }); await client.invalidateQueries({ queryKey: ["siat-sucursales"] }); } });
  const pointMutation = useMutation({ mutationFn: guardarPuntoVentaSiat, onSuccess: async () => { setPoint({ sucursalId: "", codigo: "", nombre: "" }); await client.invalidateQueries({ queryKey: ["siat-sucursales"] }); } });
  return <section className="siat-card"><div className="siat-card-title"><div><h3>Sucursales y puntos de venta</h3><p>Son códigos tributarios; no reemplazan almacenes ni cajas.</p></div><Building2 /></div>{query.isLoading && <SiatLoading />}{query.error && <SiatError message={query.error.message} />}{(query.data?.length ?? 0) > 0 && <div className="siat-branch-grid">{query.data?.map((item) => <article key={item.id}><strong>{item.codigo} · {item.nombre}</strong><small>{item.municipio ?? "Municipio pendiente"}</small><ul>{item.puntosVenta.map((pv) => <li key={pv.id}>P.V. {pv.codigo} · {pv.nombre}</li>)}</ul></article>)}</div>}<div className="siat-inline-forms"><form onSubmit={(e) => { e.preventDefault(); branchMutation.mutate({ ...branch, codigo: Number(branch.codigo) }); }}><strong>Nueva sucursal tributaria</strong><input placeholder="Código" inputMode="numeric" value={branch.codigo} onChange={(e) => setBranch((v) => ({ ...v, codigo: e.target.value }))} /><input placeholder="Nombre" value={branch.nombre} onChange={(e) => setBranch((v) => ({ ...v, nombre: e.target.value }))} /><input placeholder="Municipio" value={branch.municipio} onChange={(e) => setBranch((v) => ({ ...v, municipio: e.target.value }))} /><input placeholder="Dirección" value={branch.direccion} onChange={(e) => setBranch((v) => ({ ...v, direccion: e.target.value }))} /><button className="siat-primary-button" disabled={!/^\d+$/.test(branch.codigo) || !branch.nombre.trim()}>Guardar sucursal</button>{branchMutation.error && <small className="error">{branchMutation.error.message}</small>}</form><form onSubmit={(e) => { e.preventDefault(); pointMutation.mutate({ ...point, codigo: Number(point.codigo) }); }}><strong>Nuevo punto de venta</strong><select value={point.sucursalId} onChange={(e) => setPoint((v) => ({ ...v, sucursalId: e.target.value }))}><option value="">Selecciona sucursal</option>{query.data?.map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.nombre}</option>)}</select><input placeholder="Código" inputMode="numeric" value={point.codigo} onChange={(e) => setPoint((v) => ({ ...v, codigo: e.target.value }))} /><input placeholder="Nombre" value={point.nombre} onChange={(e) => setPoint((v) => ({ ...v, nombre: e.target.value }))} /><button className="siat-primary-button" disabled={!point.sucursalId || !/^\d+$/.test(point.codigo) || !point.nombre.trim()}>Guardar punto</button>{pointMutation.error && <small className="error">{pointMutation.error.message}</small>}</form></div></section>;
}

export default function ConfiguracionSiatModal({ onClose }: { onClose: () => void }) {
  const config = useQuery({ queryKey: ["siat-configuracion"], queryFn: obtenerConfiguracionSiat });
  return <div className="siat-modal-backdrop" role="presentation" onMouseDown={onClose}><section className="siat-modal siat-modal--large" role="dialog" aria-modal="true" aria-labelledby="siat-config-title" onMouseDown={(event) => event.stopPropagation()}><header><div><small>Administración</small><h2 id="siat-config-title">Configuración SIAT</h2></div><button type="button" onClick={onClose} aria-label="Cerrar"><X /></button></header><div className="siat-config-content">{config.isLoading && <SiatLoading />}{config.error && <SiatError message={config.error.message} />}{config.data && <ConfigForm key={JSON.stringify(config.data)} initial={config.data} />}<Operations /><PaymentMappings /><Branches /></div></section></div>;
}
