import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Eye, Settings } from "lucide-react";
import ConfiguracionSiatModal from "../../features/facturas/components/ConfiguracionSiatModal";
import { EstadoBadge, FacturaDetalleModal, SiatEmpty, SiatError, SiatLoading, SiatPageHeader } from "../../features/facturas/components/SiatShared";
import { listarFacturasSiat, obtenerEstadoSiat, obtenerRolActual } from "../../features/facturas/services/siat.service";
import type { FacturaSiatResumen } from "../../features/facturas/types/siat.types";
import "../../features/facturas/styles/siat.css";

const fecha=(v:string)=>new Intl.DateTimeFormat("es-BO",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));
export default function FacturasPage(){
 const facturas=useQuery({queryKey:["siat-facturas"],queryFn:listarFacturasSiat}); const estado=useQuery({queryKey:["siat-estado"],queryFn:obtenerEstadoSiat}); const rol=useQuery({queryKey:["usuario-rol"],queryFn:obtenerRolActual});
 const [texto,setTexto]=useState(""); const [fiscal,setFiscal]=useState("TODOS"); const [ambiente,setAmbiente]=useState("TODOS"); const [detalle,setDetalle]=useState<FacturaSiatResumen|null>(null); const [config,setConfig]=useState(false);
 const rows=useMemo(()=> (facturas.data??[]).filter(x=>`${x.numeroFactura} ${x.cliente} ${x.documento} ${x.codigoVenta} ${x.cuf??""}`.toLowerCase().includes(texto.toLowerCase())&&(fiscal==="TODOS"||x.estadoFiscal===fiscal)&&(ambiente==="TODOS"||x.ambiente===ambiente)),[facturas.data,texto,fiscal,ambiente]);
 const esAdmin=rol.data?.toLowerCase()==="administrador";
 return <div className="siat-page"><SiatPageHeader title="Gestión de facturas" description="Seguimiento comercial y fiscal de documentos, separado por estado y ambiente." action={esAdmin?<button className="siat-secondary-button" onClick={()=>setConfig(true)}><Settings/>Configuración SIAT</button>:undefined}/>
 {estado.data&&<section className="siat-health"><article><small>Servicio</small><EstadoBadge estado={estado.data.servicio}/></article><article><small>Ambiente</small><strong>{estado.data.ambiente}</strong></article><article><small>CUIS</small><EstadoBadge estado={estado.data.cuis}/></article><article><small>CUFD</small><EstadoBadge estado={estado.data.cufd}/></article><article><small>Última sincronización</small><strong>{estado.data.ultimaSincronizacion?fecha(estado.data.ultimaSincronizacion):"Pendiente"}</strong></article><article><small>Pendientes</small><strong>{estado.data.facturasPendientes}</strong></article></section>}
 {estado.error&&<SiatError message={estado.error.message}/>}<section className="siat-card"><div className="siat-toolbar"><div className="siat-search"><input value={texto} onChange={e=>setTexto(e.target.value)} placeholder="Buscar factura, cliente, NIT/CI o CUF…"/></div><select value={fiscal} onChange={e=>setFiscal(e.target.value)}><option value="TODOS">Todos los estados</option>{[...new Set((facturas.data??[]).map(x=>x.estadoFiscal))].map(x=><option key={x}>{x}</option>)}</select><select value={ambiente} onChange={e=>setAmbiente(e.target.value)}><option value="TODOS">Todos los ambientes</option><option>PRUEBAS</option><option>PRODUCCION</option></select></div>
 {facturas.isLoading?<SiatLoading/>:facturas.error?<SiatError message={facturas.error.message}/>:rows.length===0?<SiatEmpty title="Sin documentos fiscales" description="Las facturas reales aparecerán aquí cuando existan registros fiscales."/>:<div className="siat-table-wrap"><table className="siat-table"><thead><tr><th>N.º</th><th>Fecha</th><th>Cliente</th><th>NIT/CI</th><th>Venta</th><th>Total</th><th>CUF</th><th>Estado fiscal</th><th>Ambiente</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.numeroFactura}</td><td>{fecha(x.fechaEmision)}</td><td>{x.cliente}</td><td>{x.documento}</td><td>{x.codigoVenta}</td><td>Bs {x.total.toFixed(2)}</td><td title={x.cuf??"Pendiente"}>{x.cuf?`${x.cuf.slice(0,10)}…`:"Pendiente"}</td><td><EstadoBadge estado={x.estadoFiscal}/></td><td>{x.ambiente}</td><td><button className="siat-link-button" onClick={()=>setDetalle(x)} aria-label="Ver detalle"><Eye size={16}/></button></td></tr>)}</tbody></table></div>}<div className="siat-pagination">{rows.length} documento(s)</div></section>
 <FacturaDetalleModal factura={detalle} onClose={()=>setDetalle(null)} canManage={esAdmin}/>{config&&<ConfiguracionSiatModal onClose={()=>setConfig(false)}/>}</div>;
}
